name: FriendlyMobs
author: malon
version: 0.0001
description: This plugin is so 31337. You can set yourself on fire.

main: com.gmail.malonnnnn.friendlymobs.FriendlyMobs

commands:
  friendly:
    description: Spawn a friendly mob.
    permission: friendly.spawn
    usage: /friendly <mobtype>